### ISSUE TITLE
/bin/sh: php: not found 

### ISSUE THREAD

**Issue by kszymukowicz** [garvinhicking/typo3-documentation-browsersync#25]
Hi,
I was using this browsersync for a while and all was working ok. Lately I am getting some error about PHP not found.
To test it from raw I installed https://github.com/garvinhicking/demo-typo3-documentation-browsersync and here is the ouput:

```
boaa@kss demo-typo3-documentation-browsersync % docker run --rm -it --pull always \
         -v "./Documentation:/project/Documentation" \
         -v "./Documentation-GENERATED-temp:/project/Documentation-GENERATED-temp" \
         -p 5173:5173 ghcr.io/garvinhicking/typo3-documentation-browsersync:latest
latest: Pulling from garvinhicking/typo3-documentation-browsersync
Digest: sha256:47e462a6e4fa1f2ed66f472c44bfb99a291a1ffcff84be21055e0ef9fb089a6f
Status: Image is up to date for ghcr.io/garvinhicking/typo3-documentation-browsersync:latest
ENV:
LOCAL_RENDER_PORT   =
LOCAL_RENDER_INPUT  =
LOCAL_RENDER_OUTPUT =

> garvinhicking/typo3-documentation-browsersync@0.1.17 dev
> vite --host

2:24:10 PM [typo3-documentation-browsersync] Specified Documentation-GENERATED-temp/Index.html does not exist, issue first-time render.
/bin/sh: php: not found
2:24:10 PM [typo3-documentation-browsersync] Rendering Error:
-------------------
Command failed: php /opt/guides/bin/guides --no-progress --config Documentation Documentation
/bin/sh: php: not found
-------------------

2:24:10 PM [typo3-documentation-browsersync] Listening on Documentation which renders to Documentation-GENERATED-temp
2:24:10 PM [typo3-documentation-browsersync] Use e.g. http://localhost:5173/Documentation-GENERATED-temp/Index.html to view documentation.

  VITE v5.1.7  ready in 132 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: http://192.168.215.2:5173/
  ➜  press h + enter to show help
2:24:34 PM [typo3-documentation-browsersync] Render on /project/Documentation/Introduction/Index.rst
/bin/sh: php: not found
2:24:34 PM [typo3-documentation-browsersync] Rendering Error:
-------------------
Command failed: php /opt/guides/bin/guides --no-progress --config Documentation Documentation
/bin/sh: php: not found
-------------------
```

The page in browser is not refreshed - I assume because this error.

I already remove the image and it was downloaded all new but that did not helped.

Any tip what is wrong?
Tnx!

**Comment by garvinhicking** [comment]
Thanks for reporting this! Happy to hear someone is actually using this 😅

I recently had to rebuild the container because I noticed the upstream synchronization only merges the commits, but doesn't upload a new ghcr.io build. So I did that manually, end of last week.

Maybe the PHP image isn't integrated properly anymore. I will investigate this and let you know what's going on.

**Comment by garvinhicking** [comment]
Maybe you can use the "docker ... -entrypoint sh" command to enter the container and see if "/usr/bin/env php" might work, and the script is just missing a path to e.g. /usr/local/bin or so.
Will investigate myself, but probably can only do that tomorrow.

**Comment by garvinhicking** [comment]
Hey @kszymukowicz - I think I've fixed it with https://github.com/garvinhicking/typo3-documentation-browsersync/commit/0d5f43ec94692b2acb28bea3eb5b56cfffbecf75

It seems somehow(tm) the /usr/local/bin/php was no longer aliased. This wasn't due to a change from me, I guess somehow PHP or Alpine in its recent version doesn't do this... I've now changed the Dockerfile to create it, and the rendersync works again now for me. Can you check if it does for you too?

Thanks so much for bringing it to my attention.

**Comment by kszymukowicz** [comment]
@garvinhicking 

Works now perfectly! 
Tnx a lot for such a fast response.

**Comment by garvinhicking** [comment]
You're welcome, thanks the same for reporting and getting back to me quickly, now I can sleep better. :) 

Let me know if this project can do other things to help you, I'd be happy for insights on how to improve it.
