### ISSUE TITLE
Call to undefined function T3Docs\Typo3DocsTheme\Api\curl_init

### ISSUE THREAD

**Issue by dogawaf** [garvinhicking/typo3-documentation-browsersync#39]
Hi

I am trying to render the documentation with garvinhicking/typo3-documentation-browsersync and I face this issue as soon as I save a rst file:

```
Command failed: php /opt/guides/bin/guides --no-progress --config Documentation Documentation
PHP Fatal error:  Uncaught Error: Call to undefined function T3Docs\Typo3DocsTheme\Api\curl_init() in /opt/guides/packages/typo3-docs-theme/src/Api/Typo3ApiService.php:59
```

I use this command:

```
docker run --rm -it --pull always \
		-v "./Documentation:/project/Documentation" \
		-v "./Documentation-GENERATED-temp:/project/Documentation-GENERATED-temp" \
		-p 5173:5173 ghcr.io/garvinhicking/typo3-documentation-browsersync:latest
```

Rendering the docs with `make docs` is okay.

**Comment by garvinhicking** [comment]
@dogawaf Many thanks for reporting this! It seems I was missing to specify php-curl as a dependency of the package.

I've committed a fix and created a new release. Should be out in a few minutes, maybe you can retry then? It happens when ertain directives are used that may utulize a remote curl connection.

**Comment by dogawaf** [comment]
Fixed! Thanks for being so quick.
